### ISSUE TITLE
Dell Driver Cabs are Missing Model Names

### ISSUE THREAD

**Issue by BaddMann** [maurice-daly/DriverAutomationTool#432]
This is all over the place on models, but it's effecting Windows 10 Downloads the most.
As a result Driver Automation is Creating incorrect Folder Structure and my own PowerShell script looking to Verify Model Name is effected. Can Fix manually, but kind of defeats point of You awesome tool!
The CAB xml still has name, just in the Display node instead of in the Name Attribute of the Model... :(

Bad XML:
```
    <SupportedSystems>
      <Brand key="4" prefix="LAT">
        <Display lang="en"><![CDATA[ Latitude ]]></Display>
        <Model systemID="0A21" name="5520" rtsDate="2020-12-22T07:00:00" generation="X12">
          <Display lang="en"><![CDATA[ 5520 ]]></Display>
        </Model>
      </Brand>
      <Brand key="4" prefix="LAT">
        <Display lang="en"><![CDATA[ Latitude ]]></Display>
        <Model systemID="0A41" name="5520" rtsDate="2020-12-22T07:00:00" generation="X12">
          <Display lang="en"><![CDATA[ 5520 ]]></Display>
        </Model>
      </Brand>
    </SupportedSystems>
```

GoodXML:
```
    <SupportedSystems>
      <Brand key="1" prefix="OP">
        <Display lang="en"><![CDATA[ Optiplex ]]></Display>
        <Model systemID="085A" name="Optiplex 7060" rtsDate="2018-03-16" generation="">
          <Display lang="en"><![CDATA[ 7060 ]]></Display>
        </Model>
      </Brand>
      <Brand key="1" prefix="OP">
        <Display lang="en"><![CDATA[ Optiplex ]]></Display>
        <Model systemID="085D" name="Optiplex 7060" rtsDate="0001-01-01" generation="">
          <Display lang="en"><![CDATA[ 7060 ]]></Display>
        </Model>
      </Brand>
    </SupportedSystems>
```

I know this is Totally Dell's Fault, but I can't even get a hold of anyone that knows what I'm talking about....
Maybe you can have more luck? If not maybe we can Edit the model In the tool before hand?
Thanks!

**Comment by Stuart42** [comment]
Good job investigating this, we've noticed the same thing but just assumed it was Dells fault without looking further, since we didn't see it on every model recently.

**Comment by BaddMann** [comment]
Wrote Some PowerShell just to get the problem Children out of the XML:

`#.LINK
## Stolen Code From OsdDeploy to Prove Point.
#https://osddrivers.osdeploy.com/functions/get-dellmodelpack
#>
    #===================================================================================================
    # DownloadPath
    #===================================================================================================
    if (-not($DownloadPath)) {$DownloadPath = $env:TEMP}
    Write-Verbose "DownloadPath: $DownloadPath"
    #===================================================================================================
    # Dell Variables
    #===================================================================================================
    # Define Dell Download Sources
    $DellDriverPackCatalogUrl = "http://downloads.dell.com/catalog/DriverPackCatalog.cab"
    $DellCatalogPcUrl = "http://downloads.dell.com/catalog/CatalogPC.cab"
    
    # Define Dell Cabinet/XL Names and Paths
    $DellCabFile = [string]($DellDriverPackCatalogUrl | Split-Path -Leaf)
    $DellCatalogFile = [string]($DellCatalogPcUrl | Split-Path -Leaf)
    #$DellXMLFile = $DellCabFile.Trim(".cab")
    #$DellXMLFile = $DellXMLFile + ".xml"
    #$DellCatalogXMLFile = $DellCatalogFile.Trim(".cab") + ".xml"
    
    # Define Dell Global Variables
    #$global:DellCatalogXML = $null
    #$global:DellModelXML = $null
    #$global:DellModelCabFiles = $null
    #===================================================================================================
    # Driver
    #===================================================================================================
<# (New-Object System.Net.WebClient).DownloadFile($DellCatalogPcUrl, "$env:TEMP\CatalogPC.cab")
    Expand "$env:TEMP\CatalogPC.cab" "$env:TEMP\CatalogPC.xml"
    Remove-Item -Path "$env:TEMP\CatalogPC.cab" -Force
    [xml]$DellDriverCatalog = Get-Content "$env:TEMP\CatalogPC.xml" -ErrorAction Stop
    $DellDriverList = $DellDriverCatalog.DriverPackManifest.DriverPackage #>
    #===================================================================================================
    # DriverPackCatalog
    #===================================================================================================
    if (-not(Test-Path "$DownloadPath")) {New-Item "$DownloadPath" -ItemType Directory -Force | Out-Null}
    (New-Object System.Net.WebClient).DownloadFile($DellDriverPackCatalogUrl, "$DownloadPath\DriverPackCatalog.cab")

    Expand "$DownloadPath\DriverPackCatalog.cab" "$DownloadPath\DriverPackCatalog.xml" | Out-Null

    if (Test-Path "$DownloadPath\DriverPackCatalog.cab") {
        Remove-Item -Path "$DownloadPath\DriverPackCatalog.cab" -Force | Out-Null
    }

    [xml]$DriverPackageCatalog = Get-Content "$DownloadPath\DriverPackCatalog.xml" -ErrorAction Stop
    $DellDriverPackCatalog = $DriverPackageCatalog.DriverPackManifest.DriverPackage

### my code From Here on
$ModelDetails = $DriverPackageCatalog.DriverPackManifest.DriverPackage.SupportedSystems.Brand

foreach ($ModelDetail in $ModelDetails){
    $ModelDisplayName = ($ModelDetail.Display.InnerText).trim()
    $ModelName = ($ModelDetail.Model.Name).trim()
    #Write-host "$ModelName and $ModelDisplayName"
    if(!($ModelName -like "*$ModelDisplayName*") -and ($ModelDisplayName -match '^(Latitude|Optiplex|Precision)')){
        Write-host "$ModelName"
        $NewModelName = "$ModelDisplayName $ModelName"
        Write-host "Corrected: << $NewModelName >>"
    }
}`

That will list the problem children in their whole XML file. Stole some code from the excellent OsdDeploy to grab and parse the xml, but his object creation in that same script may be helpful too.
https://www.powershellgallery.com/packages/OSDDrivers/19.8.26.1/Content/Public%5CGet-DellModelPack.ps1
Looking into Re-creating the XML with the Changes saved to it, but it's outside of my normal wheelhouse and I do have real work I need to get done... 📦

**Comment by nodiaque** [comment]
I have some connection to Dell, what is the link to the bad xml from dell? I'll reach out to them

**Comment by BaddMann** [comment]
The link is in the powershell. If you run the powershell (the first one), it will also give you all the models with the bad naming schemes.Sent from my iPhoneOn Jan 10, 2023, at 12:38, Nodiaque ***@***.***> wrote:﻿
I have some connection to Dell, what is the link to the bad xml from dell? I'll reach out to them

**Comment by jlawrence1984** [comment]
Has anybody confirmed that this issue has been fixed? In the example above they listed the 5520 which I assume should have been Latitude 5520. I just launched the tool today after removing the temp files and the Latitude 5520 still is only showing up in the tool as a 5520. 
![image](https://user-images.githubusercontent.com/46609898/214373685-36375c99-1fbb-48e8-8409-df5d91b05541.png)

**Comment by nodiaque** [comment]
No it's not fixed yet, we are still waiting on Dell to fix there shit. I was just told that they are looking into it as to why it happen and will fix it but I didn't received any time line.

**Comment by BaddMann** [comment]
Run my last powershell script.It replaces the cab file with the “fixed” version in temp folder.Sent from my iPhoneOn Jan 24, 2023, at 11:12, Nodiaque ***@***.***> wrote:﻿
No it's not fixed yet, we are still waiting on Dell to fix there shit. I was just told that they are looking into it as to why it happen and will fix it but I didn't received any time line.

**Comment by guybw** [comment]
Just to confirm, this looks fixed to me!
